name: Dispatch Codegen

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  dispatch-codegen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Dispatch codegen
        uses: felleslosninger/einnsyn-codegen/.github/actions/dispatch-codegen@main
        with:
          client-id: ${{ secrets.EIN_CODEGEN_CLIENT_ID }}
          private-key: ${{ secrets.EIN_CODEGEN_APP_PRIVATE_KEY }}
          dispatch-type: sdk-typescript
          default-commit-type: fix
