name: Dispatch Codegen

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  dispatch-codegen:
    runs-on: ubuntu-latest

    env:
      commit_message: ""
      pr_body: ""

    steps:
      - name: Get token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.EIN_CODEGEN_APP_ID }}
          private-key: ${{ secrets.EIN_CODEGEN_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          skip-token-revoke: true
          repositories: |
            einnsyn-codegen

      - name: Set commit message if triggered by a PR
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.event.head_commit.message }}" == *"Merge pull request"* ]]; then
            PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=#)\d+')
            PR_TITLE=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=: ).*')
            echo "pr_body=Triggered from ${{ github.repository }} [#${PR_NUMBER}](https://github.com/${{ github.repository }}/pull/${PR_NUMBER}) ${PR_TITLE}" >> $GITHUB_ENV
            echo "commit_message=Triggered from ${{ github.repository }}#${PR_NUMBER}"
          else
            echo "pr_body=Triggered from ${{ github.repository }}" >> $GITHUB_ENV
            echo "commit_message=Triggered from ${{ github.repository }}" >> $GITHUB_ENV
          fi

      - name: Dispatch workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: felleslosninger/einnsyn-codegen
          event-type: codegen
          client-payload: |
            {
              "commit_message": "${{ env.commit_message }}",
              "pr_body": "${{ env.pr_body }}",
              "type": "sdk-typescript"
            }
